### PR TITLE
Null edge case

### PR DESCRIPTION
**Pull request by stephenmathieson**
Found an edge case where a magical `null` error snook into the `standard.tmpl`.

Now verifying the error is truthy before attempting to access its properties.

### CODE REVIEW

**Comment by stephenmathieson** [comment]
Either [Travis](https://travis-ci.org/circusbred/grunt-linter/builds/3156748) is improperly configured, or I am missing something.

Where are the failing tests?

**Comment by ShaunBaker** [comment]
Can we push this up to NPM?

**Comment by stephenmathieson** [comment]
@ShaunBaker: grunt-linter is not actively maintained due to the recent changes in [JSHint](https://github.com/jshint/jshint).

**Comment by dsturley** [comment]
@ShaunBaker published as [version 0.1.3](https://github.com/circusbred/grunt-linter/commit/c46a2bbe1f4c5ce433db204428afdf4f5f8dbb63), it should be available on npm now.  Per @stephenmathieson, JSHint has moved to CommonJS, this creates a challenge with backwards compatibility that I have no good solution for.

**Comment by dsturley** [comment]
v0.1.3 is broken, make sure you update to v0.1.4.

**Pull request merged**
